main: me.Zaynstir.Anonymous.Anonymous
name: Anonymous
version: 1
author: Zaynstir
authors: [Zaynstir, Peaceyo]
api-version: 1.15

commands:
  mask:
    description: recieve an anonymous mask.